"""Add source column to Verification model

Revision ID: 65200c084bdd
Revises: 
Create Date: 2025-12-14 21:00:50.398250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65200c084bdd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###
